### ISSUE TITLE
Useless control host since it has 2 public IPs

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/moc-inventory-prod#1]
https://github.com/CCI-MOC/moc-inventory-prod/blob/be7c0972bc28023d6ecb4a709fab430e80c70dc4/group_vars/all/moc_control_hosts.yml#L4

The host has 2 public IPs, and the other IP is the default gateway which I imagine what the iptables on the host we are trying to SSH to would see.

```
[rado@kzn-ipmi-gw ~]$ ip r |grep 128.31.28.10
128.31.28.0/24 dev eth5 proto kernel scope link src 128.31.28.10 
[rado@kzn-ipmi-gw ~]$ curl icanhazip.com
129.10.5.105
```

**Comment by naved001** [comment]
I don't even know what the other 2 control hosts are.

```
  - 129.10.5.250
  - 192.12.185.251
```
We don't have them listed on our [network documentation](https://docs.massopen.cloud/en/latest/clusters/kaizen2/Kaizen-2.html#research-ceph-vlan-252)

**Comment by larsks** [comment]
Yeah, that was just me making stuff up early on and then forgetting to remove it.
